version: '3'
services: 
    mongo:
        image: mongo:4.1.6
        restart: always
        ports:
            - 27017:27017
        networks:
            - MONGO
        volumes:
            - ./tmp/data/db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: mongoadmin
            
    mongo-express:
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
            ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
            ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
        networks:
            - MONGO
        depends_on:
            - mongo
        ports:
            - 8081:8081

    dev:
        image: nodeplusffmpeg
        volumes: 
            - .:/usr/src/service
        working_dir: /usr/src/service
        command: bash -c "npm run build && npm run server" 
        ports: 
            - 3112:3112
        networks:
            - MONGO
        depends_on:
            - mongo


    rtsp:
        image: aler9/rtsp-simple-server
        volumes: 
            - .:/usr/src/rtsp
        working_dir: /usr/src/rtsp 
        environment:
            - RTSP_PROTOCOLS=tcp
        ports: 
            - 8554:8554
            - 1935:1935
        networks:
            - MONGO
        depends_on:
            - dev
    
networks:
    MONGO:
        name: MONGO