version: '3'
services: 
    mongo:
        image: mongo:4.1.6
        restart: always
        ports:
            - 27017:27017
        networks:
            - MONGO
        # volumes:
        #     - ./tmp/data/db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: mongoadmin
            # - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            # - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
            # - MONGO_INITDB_DATABASE=project
            
    mongo-express:
        # links:
        #     - mongo
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
            ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
            ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
            # - ME_CONFIG_MONGODB_SERVER=mongoDB
            # - ME_CONFIG_MONGODB_PORT=27017
            # - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            # - ME_CONFIG_MONGODB_AUTH_DATABASE=project
            # - ME_CONFIG_OPTIONS_EDITORTHEME=3024-night
            # - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadmin
            # - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongoadmin
            # - ME_CONFIG_BASICAUTH_USERNAME=mongoexpress
            # - ME_CONFIG_BASICAUTH_PASSWORD=mongoexpress
        networks:
            - MONGO
        depends_on:
            - mongo
        ports:
            - 8081:8081

networks:
    MONGO:
        name: MONGO